FROM node:20 AS base

WORKDIR /usr/app/src

FROM base AS init

COPY . .

RUN --mount=type=bind,source=./package.json,target=/package.json \
	--mount=type=bind,source=./package-lock.json,target=/package-lock.json \
	--mount=type=bind,source=./src/,target=/src/ \
	--mount=type=bind,source=./test/,target=/test/ \
	npm ci

FROM init AS test

RUN npm run test

CMD [ "bash" ]